In [1]:
import numpy as np

In [2]:
pi = np.pi

In [3]:
def R_z(theta):
    theta = np.deg2rad(theta)
    rotate_matrix = np.array([[np.cos(theta),   np.sin(theta),  0],
                            [np.sin(theta),     np.cos(theta),  0],
                            [0,                 0,              1]])
    return rotate_matrix

In [5]:
P_a = np.array([[1],[1],[0]])

In [6]:
print(P_a)

[[1]
 [1]
 [0]]


In [7]:
P_b = np.dot(R_z(np.radians(90)),P_a)

In [8]:
print(P_b)

[[1.02703635]
 [1.02703635]
 [0.        ]]


## Translação Rotação


${}^B\mathbf{P} = {}_A^B \mathbf{R}(\theta) {}^A\mathbf{P} = 
\begin{bmatrix}
\cos(\theta) & \sin(\theta) & 0 & q_x\\
\sin(\theta) & \cos(\theta) & 0 & q_y\\
0 & 0 & 1 & q_z\\ 
0 & 0 & 0 & 1\\
\end{bmatrix}.
\begin{bmatrix}
{}^Ap_x\\
{}^Ap_y\\
{}^Ap_z\\
1
\end{bmatrix}$

In [17]:
def tf(theta, Q):
    theta = np.deg2rad(theta)
    tf_matrix = np.array([[np.cos(theta),   np.sin(theta),  0,      Q[0]],
                          [np.sin(theta),   np.cos(theta),  0,      Q[1]],
                          [0,               0,              1,      Q[2]],
                          [0,               0,              0,      1]])
    return tf_matrix

In [11]:
P_a = np.vstack((P_a, [1]))

In [12]:
print(P_a)

[[1]
 [1]
 [0]
 [1]]


In [18]:
np.dot(tf(0,[1,1,1]), P_a)

array([[2.],
       [2.],
       [1.],
       [1.]])