<a href="https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Exercício Rotação e Translação

In [0]:
import numpy as np

In [0]:
pi = np.pi

In [0]:
def R_z(theta):
    theta = np.deg2rad(theta)
    rotate_matrix = np.array([[np.cos(theta),   np.sin(theta),  0],
                            [np.sin(theta),     np.cos(theta),  0],
                            [0,                 0,              1]])
    return rotate_matrix

In [0]:
P_a = np.array([[1],[1],[0]])

In [81]:
print(P_a)

[[1]
 [1]
 [0]]


In [0]:
P_b = np.dot(R_z(np.radians(90)),P_a)

In [83]:
print(P_b)

[[1.02703635]
 [1.02703635]
 [0.        ]]


## Translação Rotação


${}^B\mathbf{P} = {}_A^B \mathbf{R}(\theta) {}^A\mathbf{P} = 
\begin{bmatrix}
\cos(\theta) & \sin(\theta) & 0 & 0\\
\sin(\theta) & \cos(\theta) & 0 & 0\\
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1\\
\end{bmatrix}.
\begin{bmatrix}
{}^Ap_x\\
{}^Ap_y\\
{}^Ap_z\\
1
\end{bmatrix}$

In [0]:
def tf(theta, Q):
    theta = np.deg2rad
    tf_matrix = np.array([[np.cos(theta),   np.sin(theta),  0,      Q[0]],
                          [np.sin(theta),   np.cos(theta),  0,      Q[1]],
                          [0,               0,              1,      Q[2]],
                          [0,               0,              0,      1]])
    return tf_matrix

In [0]:
P_a = np.vstack((P_a, [1]))

In [86]:
print(P_a)

[[1]
 [1]
 [0]
 [1]]


In [87]:
np.dot(tf(0,[1,1,1]), P_a)

array([[2.],
       [2.],
       [1.],
       [1.]])