In [1]:
import numpy as np

## Operação de Rotação

${}^A\mathbf{P} = \mathbf{R}(\theta) {}^B\mathbf{P} = 
\begin{bmatrix}
\cos(\theta) & -\sin(\theta) & 0 & q_x\\
\sin(\theta) & \cos(\theta) & 0 & q_y\\
0 & 0 & 1 & q_z\\ 
0 & 0 & 0 & 1\\
\end{bmatrix}.
\begin{bmatrix}
{}^Bp_x\\
{}^Bp_y\\
{}^Bp_z\\
1
\end{bmatrix}$

In [2]:
def rotation_matrix(theta):
    rotate_matrix = np.array([[np.cos(theta),   -np.sin(theta),  0.],
                            [-np.sin(theta),     np.cos(theta),  0.],
                            [0.,                 0.,              1.]])
    return np.round(rotate_matrix,2)

In [3]:
P_b = np.array([[1.],[0.],[0.]])

In [4]:
# exemplo da matrix de rotacao em 20 graus
rotation_matrix(np.deg2rad(20))

array([[ 0.94, -0.34,  0.  ],
       [-0.34,  0.94,  0.  ],
       [ 0.  ,  0.  ,  1.  ]])

In [5]:
print(P_b)

[[1.]
 [0.]
 [0.]]


In [6]:
P_a = np.dot(rotation_matrix(np.deg2rad(20)),P_b)

In [7]:
print(P_a)

[[ 0.94]
 [-0.34]
 [ 0.  ]]


## Transformação Homogenea


${}^A\mathbf{P} = \mathcal{A}_0^1 {}^B\mathbf{P} = 
\begin{bmatrix}
\cos(\theta) & -\sin(\theta) & 0 & q_x\\
\sin(\theta) & \cos(\theta) & 0 & q_y\\
0 & 0 & 1 & q_z\\ 
0 & 0 & 0 & 1\\
\end{bmatrix}.
\begin{bmatrix}
{}^Bp_x\\
{}^Bp_y\\
{}^Bp_z\\
1
\end{bmatrix}$

In [8]:
def th(theta, Q):
    th_matrix = np.array([[np.cos(theta),   -np.sin(theta), 0.,      Q[0]],
                          [np.sin(theta),   np.cos(theta),  0.,      Q[1]],
                          [0.,        0.,                   1.,      Q[2]],
                          [0.,        0.,                   0.,      1.]])
    return th_matrix

In [9]:
P_b = np.array([[1.],[0.],[0.]])
P_a = np.zeros((4,1))

In [10]:
P_b = np.vstack((P_b, [1]))

In [11]:
print(P_b)

[[1.]
 [0.]
 [0.]
 [1.]]


In [12]:
Q_a = np.array([3.,2.,1.])

In [13]:
P_a = np.dot(th(np.deg2rad(20),Q_a), P_b)

In [14]:
print(P_a)

[[3.93969262]
 [2.34202014]
 [1.        ]
 [1.        ]]
